package com.softcraft.calendar.MarriageMatch;

import java.text.SimpleDateFormat;
import java.util.Calendar;

//import android.support.v7.widget.helper.ItemTouchHelper.Callback;
//import cz.msebera.android.httpclient.HttpStatus;

public class AppConstants {
//    public static int[] ACTIVITY_LAUNCH_ID = new int[]{0, 0, 2, 2, 5, 6, 7, 8, 9, 9, 12, 13, 15, 16, 18, 21, 22, 23, 24, 25, 26, 27, 29, 30, 31, 32, 33, 28, 34, 35, 42, 47, 36, 4, 10, 37, 38, 39, 40, 41, 14};
//    public static String[] ACTIVITY_PREFERENCE_KEYS = new String[]{"DAY_VIEW_ACTIVITY", "DAY_VIEW_SHARE_ACTIVITY", "MONTH_VIEW_ACTIVITY", "MONTH_SHARE_VIEW_ACTIVITY", "IMPORTANT_DAYS_ACTIVITY", "THIRUKURAL_ACTIVITY", "RASI_PALAN_ACTIVITY", "MARRIAGE_MATCH_ACTIVITY", "NUMEROLOGY_NAME_ACTIVITY", "NUMEROLOGY_MATCH_ACTIVITY", "DICTIONARY_ACTIVITY", "SAMAYAL_ACTIVITY", "MEDICINE_ACTIVITY", "BEAUTY_TIPS_ACTIVITY", "YOGA_ACTIVITY", "APJ_ACTIVITY", "RIDDLE_ACTIVITY", "NOTES_ACTIVITY", "NEWS_ACTIVITY", "MATCHA_SASTHIRAM_ACTIVITY", "KANAVU_ACTIVITY", "DINAM_ORU_THAGAVAL_ACTIVITY", "PROVERB_ACTIVITY", "WISHES_ACTIVITY", "FIRST_AID_ACTIVITY", "BABY_NAMES_ACTIVITY", "ANDRU_ACTIVITY", "KIRUBANANDHAR_ACTIVITY", "SHIVA_ACTIVITY", "MANTRA_ACTIVITY", "SETTING_ACTIVITY", "JOTHIDAR_ACTIVITY", "YEAR_BOOK_ACTIVITY", DAILY_RASI_PALAN_STATUS, "PALMISTRY_ACTIVITY", "BMI_CALCULATION_ACTIVITY", "UNIT_CONVERTER_ACTIVITY", "COMPASS_ACTIVITY", "CALCULATOR_ACTIVITY", "INTEREST_ACTIVITY", "TAMIL_MOTIVATIONAL_STORIES"};
    public static String ALERT_USER_TO_BUY_CALENDAR = "ALERT_USER_TO_BUY_CALENDAR";
    public static String APJ_DATA_DOWNLOAD_STATUS = "APJ_DATA_DOWNLOAD_STATUS";
    public static final String APP_PREF_ALL_READS = "APP_PREF_ALL_READS";
    public static final String APP_PREF_BOOKMARKS = "APP_PREF_BOOKMARKS";
    public static final String APP_PREF_KEY = "whiture.tamil.calendar";
    public static String BEAUTY_TIPS_DATA_DOWNLOAD_STATUS = "APP_BEAUTY_TIPS_DATA_DOWNLOAD";
    public static final String BMI_VIEWED_STATUS = "BMI_VIEWED_STATUS";
    public static final String CALCULATOR_VIEWED_STATUS = "CALCULATOR_VIEWED_STATUS";
    public static final String CALENDAR_VIEW_MODE = "viewMode";
    public static final String COMPASS_VIEWED_STATUS = "COMPASS_VIEWED_STATUS";
    public static String DAILY_NOTIFICATION_STATUS = "DAILY_NOTIFICATION_STATUS";
    public static String DAILY_RASI_PALAN_DOWNLOAD_STATUS = "DAILY_RASI_PALAN_DOWNLOAD_STATUS";
    public static final String DAILY_RASI_PALAN_STATUS = "DAILY_RASI_PALAN_STATUS";
    public static final int DEFAULT_FONT_FACE_INDEX = 0;
    public static final int DEFAULT_FONT_SIZE_INDEX = 2;
    public static final int DEFAULT_READ_MODE_INDEX = 1;
    public static final boolean DEFAULT_SCREEN_ORIENTAION = false;
    public static String DICTIONARY_DATA_DOWNLOAD_STATUS = "APP_DICTIONARY_DATA_DOWNLOAD";
    public static String EXIT_POPUP_SHOWN_INDEX = "EXIT_POPUP_SHOWN_INDEX";
    public static final String FCM_BASE_URL = "http://139.59.4.197:8080/";
    public static String FIRST_AID_DATA_DOWNLOAD_STATUS = "FIRST_AID_DATA_DOWNLOAD_STATUS";
    public static final String HAS_SWIPE_GUIDE_SHOWN = "HAS_SWIPE_GUIDE_SHOWN";
    public static String ICON_PACK_BLUE_DOWNLOADED = "ICON_PACK_BLUE_DOWNLOADED_V29";
    public static String ICON_PACK_BLUE_FILE_NAME = "bluepackv32.zip";
    public static int ICON_PACK_FILE_SIZE = 3311440;
    public static String ICON_PACK_GREEN_DOWNLOADED = "ICON_PACK_GREEN_DOWNLOADED_V29";
    public static String ICON_PACK_GREEN_FILE_NAME = "greenpackv32.zip";
    public static String ICON_PACK_PURPLE_DOWNLOADED = "ICON_PACK_PURPLE_DOWNLOADED_V29";
    public static String ICON_PACK_PURPLE_FILE_NAME = "purplepackv32.zip";
    public static String ICON_PACK_YELLOW_DOWNLOADED = "ICON_PACK_YELLOW_DOWNLOADED_V29";
    public static String ICON_PACK_YELLOW_FILE_NAME = "yellowpackv32.zip";
    public static final String INTENT_BACKGROUND_ID = "BACKGROUND_ID";
    public static final String INTENT_BOOK_ID = "BOOK_ID";
    public static final String INTENT_CHAPTER_ID = "CHAPTER_ID";
    public static final String INTENT_FONT_FACE = "FONT_FACE";
    public static final String INTENT_FONT_SIZE = "FONT_SIZE";
    public static final String INTENT_PAGE_ID = "PAGE_ID";
    public static final String INTENT_SCREEN_ORIENTATION = "SCREEN_ORIENTATION";
    public static final String INTENT_SECTION_ID = "SECTION_ID";
    public static final String INTEREST_VIEWED_STATUS = "INTEREST_VIEWED_STATUS";
    public static final String JOTHIDAM_VIEWED_STATUS = "JOTHIDAM_VIEWED_STATUS";
    public static final String LAST_READ_BACKGROUND = "background";
    public static final String LAST_READ_BOOK = "book";
    public static final String LAST_READ_CHAPTER = "chapter";
    public static final String LAST_READ_FONT_FACE = "font_face";
    public static final String LAST_READ_FONT_SIZE = "font_size";
    public static final String LAST_READ_ORIENTATION = "orientation";
    public static final String LAST_READ_PAGE = "page";
    public static final String LAST_READ_SECTION = "section";
    public static String LAST_SAVED_VERSION = "LAST_SAVED_VERSION";
    public static String MANTHIRAMANI_DATA_DOWNLOAD_STATUS = "APP_MANTHIRAMANI_DATA_DOWNLOAD_V29";
    public static String MARRIAGE_MATCHING_DICLAIMER_SHOWN_STATUS = "APP_MARRIAGE_MATCHING_STATUS";
    public static String MEDICINE_DATA_DOWNLOAD_STATUS = "APP_MEDICINE_DATA_DOWNLOAD";
    public static final String NEWS_VIEWED_STATUS = "NEWS_VIEWED_STATUS";
    public static String NUMEROLOGY_DICLAIMER_SHOWN_STATUS = "APP_NUMEROLOGY_STATUS";
    public static String ONLINE_DATA_DOWNLOAD_MESSAGE = "நீங்கள் இப்பகுதியை முழுமையாக பயன்படுத்த ~~~~ தகவல்களை (~~~) பதிவிறக்கம் செய்ய வேண்டும்.\n\nஒரு முறை செய்தால் போதும், எப்போதும் பயன்படுத்திக் கொள்ளலாம்.";
    public static final boolean PACKAGED_BGS = false;
    public static final int PACKAGED_BOOK_ID = -1;
    public static final boolean PACKAGED_FONTS = false;
    public static String PALMISTRY_DISCLAIMER_SHOWN_STATUS = "PALMISTRY_DISCLAIMER_SHOWN_STATUS";
    public static String PALMISTRY_DOWNLOAD_STATUS = "PALMISTRY_DOWNLOAD_STATUS";
    public static String PALMISTRY_MEDU_DISCLAIMER_SHOWN_STATUS = "PALMISTRY_MEDU_DISCLAIMER_SHOWN_STATUS";
    public static String PALMISTRY_RESULT_DISCLAIMER_SHOWN_STATUS = "PALMISTRY_RESULT_DISCLAIMER_SHOWN_STATUS";
    public static String PALMISTRY_TOUR_SHOWN_STATUS = "PALMISTRY_TOUR_SHOWN_STATUS";
    public static final String PALMISTRY_VIEWED_STATUS = "PALMISTRY_VIEWED_STATUS";
    public static final String PANJANGAM_VIEWED_STATUS = "PANJANGAM_VIEWED_STATUS";
    public static final String PLANETS_VIEWED_STATUS = "PLANETS_VIEWED_STATUS";
    public static final String PRANAYAMAM_VIEWED_STATUS = "PRANAYAMAM_VIEWED_STATUS";
    public static String RATEUS_APP_CURRENT_VERSION_NO = "APP_CURRENT_VERSION_NO";
    public static String RATEUS_HAS_USER_DENIED = "RATEUS_HAS_USER_DENIED";
    public static String RATEUS_HAS_USER_RATED = "RATEUS_HAS_USER_RATED";
    public static String RATEUS_TOTAL_TIMES_OPENED = "RATEUS_TOTAL_TIMES_OPENED";
    public static String RETURN_FLAG_FOR_THEME_SETTINGS = "RETURN_FLAG_FOR_THEME_SETTINGS";
    public static String RIDDLES_DATA_DOWNLOAD_STATUS = "RIDDLES_DATA_DOWNLOAD_STATUS";
    public static String SAMAYAL_DATA_DOWNLOAD_STATUS = "SAMAYAL_DATA_DOWNLOAD_STATUS";
    public static String SAMAYAL_DATA_LOCAL_VERSION = "SAMAYAL_DATA_LOCAL_VERSION";
    public static final String SAMAYAL_IMAGES_URL = "http://kadalpura.com/nila/images/recipes/";
    public static String SAMAYAL_RECIPES_USER_FAVORITES = "SAMAYAL_RECIPES_USER_FAVORITES";
    public static String SAMAYAL_RECIPES_USER_RECENTS = "SAMAYAL_RECIPES_USER_RECENTS";
    public static final String SAVED_WEATHER_API_DATA = "SAVED_WEATHER_API_DATA";
    public static final String SELECTED_CITY_WEATHER = "SELECTED_CITY_WEATHER";
    public static final String SETTINGS_PREF_APP_LANGUAGE = "app_language";
    public static final String SETTINGS_PREF_APP_THEME = "app_theme";
    public static final String SETTINGS_PREF_DINAM_ORU_INFO_NOTIFICATION = "dinam_oru_thagaval_notification";
    public static final String SETTINGS_PREF_LAUNCH_INFO = "front_banner";
    public static final String SETTINGS_PREF_RASI_NOTIFICATION = "rasi_notification";
    public static final String SETTINGS_PREF_TODAY_SPECIAL_NOTIFICATION = "today_special_notification";
    public static String SHIVA_TEMPLES_DATA_DOWNLOAD_STATUS = "SHIVA_TEMPLES_DATA_DOWNLOAD_STATUS";
    public static final String SOLITAIRE_PROMO_STATUS = "SOLITAIRE_PROMO_STATUS";
    public static final String STORE_VIEWED_STATUS = "STORE_VIEWED_STATUS";
    public static final String TAMIL_CALENDAR_ICONS_URL = "http://kadalpura.com/tamil_calendar/icons/";
    public static final String TAMIL_MOTIVATIONAL_VIEWED_STATUS = "TAMIL_MOTIVATIONAL_VIEWED_STATUS";
    public static final String THANGLISH_SELECTED_STATUS = "THANGLISH_SELECTED_STATUS";
    public static String TOUR_SHOWN_STATUS = "TOUR_SHOWN_STATUS";
    public static final String UNIT_CONVERTER_VIEWED_STATUS = "UNIT_CONVERTER_VIEWED_STATUS";
    public static final String USER_HAD_SHOWN_GESTURES_HELP = "USER_HAD_SHOWN_GESTURES_HELP";
    public static String USER_HOROSCOPE_STAR = "USER_HOROSCOPE_STAR";
    public static String USER_LAST_APP_USAGE = "USER_LAST_APP_USAGE";
    public static String VARIYAAR_DATA_DOWNLOAD_STATUS = "APP_VARIYAAR_DATA_DOWNLOAD";
    public static final String WEATHER_API_URL = "http://api.openweathermap.org/data/2.5/weather?id=1264521&APPID=b877d8a01f74c37c732c644d8876cab9&units=metric";
    public static String YEAR_BOOK_DATA_DOWNLOAD_STATUS = "YEAR_BOOK_DATA_DOWNLOAD_STATUS";
    public static String YEAR_BOOK_DATA_DOWNLOAD_STATUS_EIGHTEEN = "YEAR_BOOK_DATA_DOWNLOAD_STATUS_EIGHTEEN";
    public static String YEAR_DATA_DOWNLOAD_STATUS = "YEAR_DATA_DOWNLOAD_STATUS";
    public static final String YEAR_DATA_TANGLISH_URL = "http://kadalpura.com/tamil_calendar/data/year_data_thanglish.zip";
    public static final String YEAR_DATA_URL = "http://kadalpura.com/tamil_calendar/data/year_data.zip";
    public static String YEAR_THANGLISH_DATA_DOWNLOAD_STATUS = "YEAR_THANGLISH_DATA_DOWNLOAD_STATUS";
    public static String YOGA_DATA_DOWNLOAD_STATUS = "YOGA_DATA_DOWNLOAD_STATUS";
    public static final String beautyArticlesFilePath = "/beauty_tips_data/beauty_tips_data_article_title_data.txt";
    public static final String beautyPartsFilePath = "/beauty_tips_data/beauty_tips_data_partsdata.txt";
    public static final String beautyProblemsFilePath = "/beauty_tips_data/beauty_tips_data_problemsdata.txt";
    public static final String beautyThingsFilePath = "/beauty_tips_data/beauty_tips_data_thingsdata.txt";
    public static final String[] englishDays = new String[]{"SUNDAY", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY"};
    public static final String[] englishMonths = new String[]{"January", "February", "March ", "April ", "May ", "June", "July", "August ", "September", "October ", "November", "December"};
    public static final String[] englishMonthsInTamil = new String[]{"ஜனவரி", "பிப்ரவரி", "மார்ச்", "ஏப்ரல்", "மே", "ஜூன்", "ஜூலை", "ஆகஸ்ட்", "செப்டம்பர்", "அக்டோபர்", "நவம்பர்", "டிசம்பர்"};
//    public static final int[] getthagavalIndices = new int[]{284, 110, 152, 30, 47, 38, 60, 95, 12, 90, 63, 13, 5, 15, 87, 165, 11, 20, 88, 14, 16, 19, 93, 21, 91, 22, 119, 18, 23, 17, 26, 28, 55, 107, 27, 54, 25, 24, 126, 227, 189, 156, 108, 190, 111, 56, 212, 225, 226, 57, 106, 157, 213, 228, 80, 53, 158, 191, 230, 58, 159, 29, 160, 155, 161, 31, 214, 192, 167, 231, 254, 82, 94, 216, 112, 105, 232, HttpStatus.SC_USE_PROXY, 325, 339, 340, 326, 306, 168, 193, 61, 162, 255, 194, 233, 256, 217, 59, 163, 96, 104, 218, 169, 114, 52, 224, 115, 195, 235, InputDeviceCompat.SOURCE_KEYBOARD, 116, 258, 223, 259, 222, 221, 219, 3, 172, 164, 4, 165, 62, 117, 113, 166, 196, 6, 197, 167, 220, 198, 173, 51, 220, 103, 188, 7, 118, 168, 200, 8, 236, HttpStatus.SC_SEE_OTHER, 341, 237, HttpStatus.SC_NOT_MODIFIED, 175, 1, HttpStatus.SC_ACCEPTED, 65, HttpStatus.SC_NON_AUTHORITATIVE_INFORMATION, 64, 169, 9, 102, HttpStatus.SC_NO_CONTENT, 238, 327, 120, 342, 239, 88, 170, 260, HttpStatus.SC_TEMPORARY_REDIRECT, 187, 171, 176, HttpStatus.SC_RESET_CONTENT, 261, 174, 324, 328, 262, 308, HttpStatus.SC_PARTIAL_CONTENT, 66, 122, 177, 10, HttpStatus.SC_MULTI_STATUS, 240, HttpStatus.SC_MOVED_TEMPORARILY, 263, 89, 309, 265, 343, HttpStatus.SC_CREATED, 241, 199, 101, 266, 329, 311, 267, 344, 330, 310, 268, HttpStatus.SC_MOVED_PERMANENTLY, 48, 67, 123, 178, 49, 208, 242, 312, 269, 50, 270, 243, 271, HttpStatus.SC_MULTIPLE_CHOICES, 100, 209, 244, 229, 299, 264, 272, 215, 124, 179, 68, 109, 245, 273, 46, 69, 210, 45, 274, 275, 298, 276, 2, 211, 125, 234, 99, 70, 180, 313, 277, 278, 246, 279, 314, 323, 40, 297, 315, 331, 345, 347, 247, 41, 127, 154, 181, 42, 280, 316, 332, 281, 346, 296, 44, 182, 92, 43, 97, 248, 98, 282, 333, 348, 317, 128, 153, 183, 283, 287, 295, 318, 288, 289, 185, 249, 285, 334, 349, 352, 286, 186, 129, 71, 151, Callback.DEFAULT_SWIPE_ANIMATION_DURATION, 37, 290, 319, 335, 350, 291, 353, 141, 320, 39, 336, 351, 354, 337, 91, 142, 90, 251, 292, 321, 130, 72, 143, 131, 139, 140, 144, 150, 184, 252, 145, 293, 322, 294, 89, 355, 338, 253, 85, 86, 73, 138, 36, 137, 146, 149, 35, 136, 81, 79, 83, 132, 78, 92, 84, 87, 133, 148, 34, 147, 74, 134, 33, 76, 135, 77, 75, 32};
    public static final String[] hooraiTimings = new String[]{"6.00 - 7.00", "7.00 - 8.00", "8.00 - 9.00", "9.00 - 10.00", "10.00 - 11.00", "11.00 - 12.00", "12.00 - 1.00", "1.00 - 2.00", "2.00 - 3.00", "3.00 - 4.00", "4.00 - 5.00", "5.00 - 6.00"};
    public static boolean isNewIconsAvailableForTheCurrentVersion = true;
    public static final String sidhdhaPartsFilePath = "/medicine_tips_data/medicine_partsdata.txt";
    public static final String sidhdhaProblemsFilePath = "/medicine_tips_data/medicine_problemsdata.txt";
    public static final String sidhdhaThingsFilePath = "/medicine_tips_data/medicine_thingsdata.txt";
    public static final String[] tamilMonthPairs = new String[]{"மார்கழி - தை", "தை - மாசி", "மாசி - பங்குனி", "பங்குனி - சித்திரை", "சித்திரை - வைகாசி", "வைகாசி -ஆனி", "ஆனி - ஆடி", "ஆடி - ஆவணி", "ஆவணி -புரட்டாசி", "புரட்டாசி- ஐப்பசி", "ஐப்பசி - கார்த்திகை", "கார்த்திகை - மார்கழி"};
    public static final String[] tamilMonths = new String[]{"சித்திரை", "வைகாசி", "ஆனி", "ஆடி", "ஆவணி", "புரட்டாசி", "ஐப்பசி", "கார்த்திகை", "மார்கழி", "தை", "மாசி", "பங்குனி"};
    public static final String[] tamilWeekdays = new String[]{"ஞாயிறு", "திங்கள்", "செவ்வாய்", "புதன்", "வியாழன் ", "வெள்ளி", "சனி"};
    public static final String[] tamilWeekdaysShort = new String[]{"ஞாயி", "திங்", "செவ்", "புத", "வியா", "வெள்", "சனி"};
    public static final String[] thanglishMonthPairs = new String[]{"Margali - Thai", "Thai - Maasi", "Maasi - Panguni", "Panguni - Chithirai", "Chithirai - Vaikasi", "Vaikasi - Aani", "Aani - Aadi", "Aadi - Aavani", "Aavani - Puratasi", "Puratasi- Aipasi", "Aipasi - Karthigai", "Karthigai - Margali"};
    public static final String[] thanglishTamilMonths = new String[]{"Chithirai", "Vaikasi", "Aani", "Aadi", "Aavani", "Puratasi", "Aipasi", "Karthigai", "Margali", "Thai", "Maasi", "Panguni"};
    public static final String[] thanglishWeekdaysShort = new String[]{"SUN", "MON", "TUE", "WED", "THU", "FRI", "SAT"};

    public static String getDateTimeFromMillis(long j, String str) {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat(str);
        Calendar instance = Calendar.getInstance();
        instance.setTimeInMillis(j);
        return simpleDateFormat.format(instance.getTime());
    }


}
